name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x', '9.0.x' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Restore dependencies
        run: dotnet restore SGuard.DataAnnotations.sln
      - name: Build solution
        run: dotnet build SGuard.DataAnnotations.sln --no-restore --configuration Release
      - name: Run tests
        run: dotnet test SGuard.DataAnnotations.Tests/SGuard.DataAnnotations.Tests.csproj --no-build --configuration Release --verbosity normal --logger trx --settings coverlet.runsettings
      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: SGuard.DataAnnotations.Tests/TestResults/*.trx
      - name: Check formatting
        run: dotnet format --verify-no-changes
      - name: Check for outdated NuGet packages
        run: dotnet list SGuard.DataAnnotations/SGuard.DataAnnotations.csproj package --outdated
