name: Coverage & README

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x', '9.0.x' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Restore dependencies
        run: dotnet restore SGuard.DataAnnotations.sln
      - name: Build solution
        run: dotnet build SGuard.DataAnnotations.sln --no-restore --configuration Release
      - name: Run tests with coverage
        run: dotnet test SGuard.DataAnnotations.Tests/SGuard.DataAnnotations.Tests.csproj --no-build --configuration Release --collect:"XPlat Code Coverage" --settings coverlet.runsettings
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: SGuard.DataAnnotations.Tests/TestResults/

  update-readme:
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
      - name: Update README with coverage badge (custom step)
        run: echo "Coverage badge update step goes here. Integrate with shields.io or similar if needed."
